### ISSUE TITLE
ISSUE: This repo is centered around harassing a person and their baby sister.

### ISSUE THREAD

**Issue by iphoneisdestroyedbyyoucheckra1n** [RDS5/shujav2#3]
The title is self explanatory, even if he did lie (unlikely, I know him IRL) you can't just leak photo's of him and his baby sister and use it against him, nor can you blame him for getting a fever.

**Comment by halal-beef** [comment]
least obvious shuja alt

**Comment by halal-beef** [comment]
also exposing someone for their bullshit is considered harassment? Grow up

**Comment by halal-beef** [comment]
Also every. Single. Thing. Was public info, his phone number was completely public and any pictures were from his WhatsApp profile picture

**Comment by halal-beef** [comment]
Also let's bring up some agreements shall we?

**Comment by halal-beef** [comment]
![Uploading Screenshot_20230514-141846_Discord~2.png…]()

**Comment by halal-beef** [comment]
![Uploading Screenshot_20230514-141846_Discord~2.png…]()

**Comment by halal-beef** [comment]
https://media.discordapp.net/attachments/1068258322161086526/1107296402465378344/Screenshot_20230514-141846_Discord2.png

**Comment by halal-beef** [comment]
That's u clearly agreeing to the video being released if any source was not released

**Comment by halal-beef** [comment]
![Screenshot_20230514-141846_Discord~2](https://github.com/RDS5/shujav2/assets/78730004/6250b95a-adcd-43d2-8274-136e9038576f)

**Comment by halal-beef** [comment]
Just remember, from January 5 2022 to May 13 2023 you had so much chances to post source, yet u didnt

**Comment by RDS5** [comment]
@iphoneisdestroyedbyyoucheckra1n this video had a single photo of their baby sister, which fit in with the script "he started off like any other dev"
might remove it as your family doesn't have anything to do with this, and you're the only one doing anything wrong.

also shuja i know this is your alt, you told us this at some point. we are not stupid..

**Comment by RDS5** [comment]
issue will be reopened if you stop acting like a crybaby and try to have a logical conversation with us for once instead of fading into the shadows everytime. (like you did with the haxberry and mighty issue #8)

**Comment by RDS5** [comment]
i accidentally clicked reopen with comment (i am tarded)
